export enum TransactionStateus {
  WAITING_APPROVE = 'WAITING_APPROVE',
  SHIPPED = 'SHIPPED',
  CANCELLED = 'CANCELLED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
}
